# Generated by Django 5.0.2 on 2024-03-08 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_product_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
